# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 02:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0028_merge'),
        ('wagtailimages', '0012_copy_image_permissions_to_collections'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('header_title', models.CharField(max_length=255)),
                ('slogan', models.CharField(max_length=255)),
                ('button_text', models.CharField(max_length=255)),
                ('s1_heading', wagtail.wagtailcore.fields.RichTextField()),
                ('s1_body', wagtail.wagtailcore.fields.RichTextField()),
                ('s2_heading', wagtail.wagtailcore.fields.RichTextField()),
                ('s3_heading', wagtail.wagtailcore.fields.RichTextField()),
                ('s3_tagline', wagtail.wagtailcore.fields.RichTextField()),
                ('service_1_title', wagtail.wagtailcore.fields.RichTextField()),
                ('service_2_title', wagtail.wagtailcore.fields.RichTextField()),
                ('service_2_price', models.IntegerField(default=289, max_length=3)),
                ('s4_heading', wagtail.wagtailcore.fields.RichTextField()),
                ('s4_call_to_action', wagtail.wagtailcore.fields.RichTextField()),
                ('s4_lbutton_text', models.CharField(max_length=20)),
                ('s4_rbutton_text', models.CharField(max_length=20)),
                ('header_background_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image')),
                ('logo_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image')),
                ('s1_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('style', models.IntegerField(max_length=1)),
                ('name', models.CharField(max_length=255)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='icons', to='home.HomePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=30)),
                ('number', models.CharField(max_length=20, null=True)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial')], max_length=15)),
                ('message_date', models.DateTimeField(auto_now_add=True)),
                ('contacted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('body', wagtail.wagtailcore.fields.RichTextField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='home.HomePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
