# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 03:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0012_copy_image_permissions_to_collections'),
        ('home', '0002_auto_20160404_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=30)),
                ('number', models.CharField(max_length=20, null=True)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial')], max_length=15)),
                ('contact_date', models.DateTimeField(auto_now_add=True)),
                ('contacted', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.RemoveField(
            model_name='reason',
            name='page',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='button_text',
            new_name='header_button',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='s1_body',
            new_name='s1_text',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='s2_heading',
            new_name='s2_text',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='s3_heading',
            new_name='s3_text',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='s4_call_to_action',
            new_name='s4_text',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='service_2_price',
            new_name='service2_price',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='header_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='s1_heading',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='s3_tagline',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='s4_heading',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='s4_lbutton_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='s4_rbutton_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='service_1_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='service_2_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='slogan',
        ),
        migrations.AddField(
            model_name='homepage',
            name='header_text',
            field=wagtail.wagtailcore.fields.RichTextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='parralax_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service1',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='service2',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homepage',
            name='header_background_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.DeleteModel(
            name='Reason',
        ),
    ]
