# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20160408_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='category',
            field=models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial')], default='Residential', max_length=15),
        ),
    ]
