---
- name: Authorized hosts for bitbucket
  shell: ssh-keyscan -H bitbucket.org >> /home/{{ deploy_user }}/.ssh/known_hosts
  when: vcs == 'hg'
  args:
      creates: /home/{{ deploy_user }}/.ssh/known_hosts
  become: no
  tags:
      - hg
      - test

- name: Authorized hosts for github
  shell: ssh-keyscan github.com 192.30.252.131 >> /home/{{ deploy_user }}/.ssh/known_hosts
  become: yes
  when: vcs == 'git'
  tags:
      - hg
      - test


- name: Create the Sites Directory if not present 
  file: path={{ sites_dir }}/{{ project_name }} owner={{ deploy_user }} group={{ deploy_user }} state=directory
  become: yes
  become_user: root
  tags:
      - web 

 - name: Prompt to add deploy key to VCS
   pause: prompt="Ensure you've added the key for the deploy user (located in the authorized keys dir) to the git directory for the project.
                  Please press [Enter] after you've added keys" 
   tags:
     - user
      - hg

- name: clone git repo 
  git: repo={{ project_repo }} dest={{ sites_dir }}/{{ project_name }}
  become: yes
  become_user: "{{ deploy_user }}"
  when: vcs == 'git'
  tags:
      - web 
      - hg
        
- name: clone hg repo
  command: hg clone {{ project_repo }} 
  when: vcs == 'hg'
  become: no
  args:
      chdir: "{{ sites_dir }}"
      creates: "{{ sites_dir }}/{{ project_name }}"
  tags:
      - web 
      - hg
