---
- name: update the apt-cache
  apt: update_cache=yes 
  become: yes
  tags:
    - bower

'''
- name: install bower and dependencies
  become: yes
  apt: >
        pkg={{ item }}  
        state=latest
        force=yes
  with_items:
    - nodejs 
    - npm
    - nodejs-legacy
  tags:
    - bower
    - node
'''
- name: install bower and dependencies
  become: yes
  curl: curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash - && sudo apt-get install -y nodejs

- name: install bower 
  become: yes
  shell: npm install -g bower
  tags:
     - bower

- name: install frontend dependencies 
  become: no
  shell: bower install
  args:
     chdir: "{{ sites_dir }}/{{ project_name }}"
  tags:
     - bower 
